### PR TITLE
Python REPL (serial input) support

### PR DESCRIPTION
**Pull request by dunkmann00**
This PR enables use of the Python REPL with a CircuitPython device just like in the Mu Editor.

### CODE REVIEW

**Comment by dunkmann00** [comment]
Hey @jos-b, any interest in this PR?

**Comment by jos-b** [comment]
Hey @dunkmann00! Huge apologies, I completely missed this PR.

I'll give it a test now, thank you!

**Comment by jos-b** [comment]
This works great! Thank you for the contribution!

**Comment by jos-b** [comment]
I'll push this out now in v0.7.0, I think it warrants a release alone!

**Comment by jos-b** [comment]
Published

**Comment by dunkmann00** [comment]
Great! I appreciate it!

**Pull request merged**
